version: "3.1"
services:
  node:
    image: "node:14.15.2"
    user: "node"
    working_dir: /home/node/app
    restart: always
    depends_on:
      - mongo
    environment:
      - .env
    volumes:
      - ./api/:/home/node/app
      - ./api/node_modules:/home/node/app/node_modules
    ports:
      - "8082:3000"
    command: "npm start"
  mongo:
    image: mongo
    restart: always
    volumes:
      - "./data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "8083:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
